-- Moonshine Saints schema (PostgreSQL). Run in the Supabase SQL editor.

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('songwriter', 'gig_lead', 'member')),
  is_admin BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Codes are generated by an admin before the user exists; one code per member (fixed 6).
CREATE TABLE invite_codes (
  code TEXT PRIMARY KEY,
  name TEXT, -- optional: pre-fills the member's name on sign-up
  used_by INT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE songs (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  lead_singer_id INT REFERENCES users(id),
  is_duet BOOLEAN NOT NULL DEFAULT FALSE,
  second_singer_id INT REFERENCES users(id), -- only set for duets
  songwriters INT[] NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'WIP' CHECK (status IN ('WIP', 'Final')),
  lyrics TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX idx_songs_name ON songs (lower(name));

CREATE TABLE tabs (
  id SERIAL PRIMARY KEY,
  song_id INT NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
  version_number INT NOT NULL DEFAULT 1,
  is_minor_edit BOOLEAN NOT NULL DEFAULT FALSE,
  capo INT,
  tuning TEXT,
  key TEXT,
  tempo INT,
  source_type TEXT NOT NULL DEFAULT 'original' CHECK (source_type IN ('original', 'cover', 'ug_link', 'ug_file')),
  source_url TEXT,
  chordpro_source TEXT NOT NULL,
  display_format JSONB,
  created_by INT REFERENCES users(id),
  created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX idx_tabs_song_id ON tabs(song_id);

CREATE TABLE recordings (
  id SERIAL PRIMARY KEY,
  tab_id INT NOT NULL UNIQUE REFERENCES tabs(id) ON DELETE CASCADE, -- one per tab version
  file_url TEXT NOT NULL,
  file_type TEXT NOT NULL CHECK (file_type IN ('mp3', 'youtube', 'voice_memo')),
  duration_seconds INT,
  uploaded_by INT REFERENCES users(id),
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE gigs (
  id SERIAL PRIMARY KEY,
  name TEXT, -- optional label, e.g. 'Fall Kickoff'
  venue TEXT NOT NULL,
  date DATE NOT NULL,
  time TIME,
  created_by INT REFERENCES users(id),
  created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX idx_gigs_date ON gigs(date);

CREATE TABLE setlist_items (
  id SERIAL PRIMARY KEY,
  gig_id INT NOT NULL REFERENCES gigs(id) ON DELETE CASCADE,
  song_id INT NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
  position INT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX idx_setlist_gig_id ON setlist_items(gig_id);

CREATE TABLE messages (
  id SERIAL PRIMARY KEY,
  thread_id INT REFERENCES messages(id) ON DELETE CASCADE, -- NULL for thread root
  content TEXT NOT NULL,
  sender_id INT NOT NULL REFERENCES users(id),
  parent_message_id INT REFERENCES messages(id) ON DELETE CASCADE,
  song_id INT REFERENCES songs(id) ON DELETE SET NULL, -- optional tag on a thread's root message
  gig_id INT REFERENCES gigs(id) ON DELETE SET NULL,
  is_resolved BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX idx_messages_thread_id ON messages(thread_id);
CREATE INDEX idx_messages_created_at ON messages(created_at DESC);
CREATE INDEX idx_messages_fts ON messages USING GIN (to_tsvector('english', content));

CREATE TABLE comments (
  id SERIAL PRIMARY KEY,
  tab_id INT NOT NULL REFERENCES tabs(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  commenter_id INT NOT NULL REFERENCES users(id),
  is_resolved BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX idx_comments_tab_id ON comments(tab_id);
